31 announcement
Empower-HR/BE-Empower-HR pull request #37
Opened 2024-07-29 03:44 UTC by fajar2302

Fitur Announcement  : GET & POST Announcement

2024-07-29 03:47 UTC, jackthepanda96 requested changes

2024-07-29 03:47 UTC, jackthepanda96 commented on features/Announcement/handler/handler.go
> +		attchmentURL, err := ah.cloudinaryUtility.UploadCloudinary(src, attachment.Filename)
cloudinary manggilnya di service mas

2024-07-29 04:56 UTC, fajar2302 commented on features/Announcement/handler/handler.go
> +		attchmentURL, err := ah.cloudinaryUtility.UploadCloudinary(src, attachment.Filename)
Ohhh okee mas

2024-07-30 03:12 UTC, jackthepanda96 approved these changes

2024-07-30 07:59 UTC, riandarmawann approved these changes

2024-07-30 07:59 UTC, merged