fixing attendance and add filter by status
Empower-HR/BE-Empower-HR pull request #40
Opened 2024-07-29 11:52 UTC by fajar2302

2024-07-29 17:04 UTC, jackthepanda96 requested changes

2024-07-29 17:04 UTC, jackthepanda96 commented on features/Attendance/handler/handler.go
> +	fmt.Println("Data-Handler: ",result)
kalo ga dipake dihapus aja

2024-07-30 03:13 UTC, jackthepanda96 approved these changes

2024-07-30 07:56 UTC, riandarmawann approved these changes

2024-07-30 07:58 UTC, merged